{{/*
  
  Copyright 2026 The OKDP Authors.
  
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
  http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

*/}}

{{- /*
  Creates a Secret suitable for nginx.ingress.kubernetes.io/auth-secret
  It writes an htpasswd "auth" file using Helm/Sprig htpasswd function.
*/ -}}

{{- $cfg := .Values.filer.auth -}}
{{- if and $cfg (eq ($cfg.method | default "") "basic") $cfg.basic $cfg.basic.create_auth_secret }}

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $cfg.basic.create_auth_secret | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "auth-config.labels" . | nindent 4 }}
    app.kubernetes.io/component: filer
stringData:
  # nginx ingress basic auth expects the key to be named "auth"
  # and contain htpasswd-formatted content.
  auth: |-
    {{ htpasswd ($cfg.basic.username | required "filer.auth.basic.username is required") ($cfg.basic.password | required "filer.auth.basic.password is required") }}
{{- end }}
