{{/*
Wrapper helpers. Prefixed okdp-jupyterhub. so they never collide with the
partials of the vendored charts (jupyterhub.*, spark-rbac.*, oidc-client.*).
*/}}

{{/* Public URL: https://jupyterhub-<namespace>.<ingress suffix>. */}}
{{- define "okdp-jupyterhub.url" -}}
{{- include "okdp.url" . -}}
{{- end -}}

{{/*
OAuth client of the kubauth mode: the clients live in one shared namespace,
so the name carries the project namespace (two same-named releases of two
projects would otherwise share a client).
*/}}
{{- define "okdp-jupyterhub.kubauthClient" -}}
{{- printf "%s-%s" .Release.Name .Release.Namespace -}}
{{- end -}}

{{/*
Secret with the OAuth client (client_id, client_secret, JUPYTERHUB_CRYPT_KEY):
the one this chart generates in the kubauth mode (module oidc-client), else
the creds-<release>-oauth2 convention of the existing mode.
*/}}
{{- define "okdp-jupyterhub.oauthSecret" -}}
{{- if (include "okdp.oidc" . | fromYaml).kubauth.enabled -}}
{{- printf "%s-oidc-creds" (include "okdp-jupyterhub.kubauthClient" .) -}}
{{- else -}}
{{- printf "creds-%s-oauth2" .Release.Name -}}
{{- end -}}
{{- end -}}

{{/*
Secret the oidc-dcr job writes the registered client to (dcr mode), keys
client_id and client_secret; JUPYTERHUB_CRYPT_KEY then comes from the
generated hub passwords (hub.config.CryptKeeper.keys).
*/}}
{{- define "okdp-jupyterhub.dcrSecret" -}}
{{- printf "%s-%s-dcr" .Release.Name .Release.Namespace -}}
{{- end -}}

{{/* Scopes the hub requests at login (the oidc-dcr registration must grant them, openid aside). */}}
{{- define "okdp-jupyterhub.scope" -}}
openid profile email groups
{{- end -}}

{{/* The hub Secret of the jupyterhub chart: <fullname>-hub, fullname being the release name. */}}
{{- define "okdp-jupyterhub.hubSecret" -}}
{{- include "okdp.fullname" (dict "ctx" . "suffix" "hub") -}}
{{- end -}}

{{/*
Values the jupyterhub chart would generate with lookup + randAlphaNum. The
chart is handed this placeholder so that it renders nothing random; the hub
Secret carrying the real values is generated by ESO (templates/jupyterhub.yaml),
and the hub pops these keys from hub.config before applying it.
*/}}
{{- define "okdp-jupyterhub.generatedPlaceholder" -}}
generated-by-external-secrets
{{- end -}}

{{/*
okdp-jupyterhub.placeholders: replaces the placeholders a free-text parameter
(welcomeNotebook, sparkDefaults) may carry, in their Helm and KuboCD forms.
Takes a dict {ctx, text}.
*/}}
{{- define "okdp-jupyterhub.placeholders" -}}
{{- $ctx := .ctx -}}
{{- $suffix := toString $ctx.Values.global.okdp.ingress.suffix -}}
{{- .text
    | replace "{{ .Values.global.okdp.ingress.suffix }}" $suffix
    | replace "{{ .Context.ingress.suffix }}" $suffix
    | replace "{{ .Release.Name }}" $ctx.Release.Name
    | replace "{{ .Release.metadata.name }}" $ctx.Release.Name
    | replace "{{ .Release.Namespace }}" $ctx.Release.Namespace
    | replace "{{ .Release.namespace }}" $ctx.Release.Namespace -}}
{{- end -}}
